version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        image: php:8.2.4RC1-fpm
        volumes:
            - ./src:/var/www/html